version: '3.1'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "RedVenture"
      MYSQL_ROOT_PASSWORD: "password"
  web:
    image: python
    ports:
      - 5000:5000
    build: .
    command: bash -c "python3 /code/src/unit_test.py && python3 /code/src/MarkupProject.py"
    depends_on:
      - db
    volumes:
      - .:/code
